name: Test ScaffoldLang

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        
    - name: Build
      run: cargo build --release
      
    - name: Basic Test
      run: |
        ls -la target/release/
        echo "Build completed successfully"
